name: ViaRewindPotions
version: 0.0.2
description: Translates thrown potions for ProtocolSupport and ViaRewind
depend: [ProtocolLib]
api-version: 1.13
softdepend:
  - "ProtocolSupport"
  - "ViaRewind"
  - "ViaRewind-Legacy-Support"
main: twolovers.viarewindpotions.Main