name: ViaRewindPotions
version: 0.0.2
description: Translates thrown potions for ProtocolSupport and ViaRewind
depend: [ProtocolLib]
softdepend:
  - "ProtocolSupport"
  - "ViaRewind"
  - "ViaRewind-Legacy-Support"
main: dev._2lstudios.viarewindpotions.Main